name: zapfull-security-scan
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  

    - name: Checkout
      uses: actions/checkout@v4
      
    - name: OWASP ZAP Full Scan
      uses: zaproxy/action-full-scan@v0.1.0
      with:
        target: "google.com"
